import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Container, Nav, Navbar, Row, Col } from 'react-bootstrap'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <header >
          <Container fluid>
            <Row >
              <Col xl={7} lg={7}>
                <Navbar.Brand href="#home">Brand link</Navbar.Brand>
              </Col>
              <Col xl={5} lg={5}>
                <Nav className="me-auto" style={{ display: 'flex', justifyContent: 'flex-end'}}>
                  <Nav.Link href="#home">Home</Nav.Link>
                  <Nav.Link href="#features">Features</Nav.Link>
                  <Nav.Link href="#pricing">Pricing</Nav.Link>
                </Nav>
              </Col>
            </Row>
          </Container>
          <Container fluid>
            <Navbar>
              <Row >
                <Col xl={7} lg={7}>
                  <Navbar.Brand href="#home">Brand link</Navbar.Brand>
                </Col>
                <Col xl={5} lg={5}>
                  <Nav className="me-auto" style={{ display: 'flex', justifyContent: 'flex-end'}}>
                    <Nav.Link href="#home">Home</Nav.Link>
                    <Nav.Link href="#features">Features</Nav.Link>
                    <Nav.Link href="#pricing">Pricing</Nav.Link>
                  </Nav>
                </Col>
              </Row>
            </Navbar>
          </Container>
      </header>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
